# Virtual Machine Configuration
os:
  - linux
  - osx

# Project JDK
language: java
jdk:
  - openjdk11
  - oraclejdk11

branches:
  only:
    - master
    
notifications:
  email:
    recipients:
      - samuelfumerohdez@gmail.com
      
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# Package will be tested in every OS
script: mvn clean verify

# Using Build Stages to avoid generation documentation and deployment multiple times
stages:
  - sonar
  - deploy

jobs:
  include:
    # Executing sonar analysis only once
    - stage: sonar
      os: linux
      jdk: openjdk11
      # Sonar Plugin
      addons:
        sonarcloud:
          organization: "ldhlogistica"
      # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

    # Deploying documentation only once
    - stage: deploy
      os: linaux
      jkd: openjdk11
      # Doxygen Packages
      #addons:
       # apt:
        #  packages:
         #   - doxygen
          #  - doxygen-doc
           # - doxygen-latex
            #- doxygen-gui
            #- graphviz
      # generate documentation using Doxyfile config
      #script: doxygen Doxyfile
      # GitHub Pages Deployment
      deploy:
        provider: pages
        strategy: git
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        #local_dir: docs/html
        on:
          branch: master
    
    
    
    
    
    
    
   
   

